version: "3.8"

services:
  goservice:
    container_name: goservice
    build: "."
    ports:
    - "8080:8080"
    networks:
      testnet:
        ipv4_address: 10.5.0.5
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8084:80"
    networks:
     testnet:
       ipv4_address: 10.5.0.6
    depends_on:
      - "goservice"

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
